### ISSUE TITLE
Test Kitchen fails on test

### ISSUE THREAD

**Issue by strangeman** [express42-cookbooks/openvpn#9]
```
   ================================================================================
   Recipe Compile Error in /tmp/kitchen/cache/cookbooks/openvpn_test/recipes/bridged.rb
   ================================================================================

   Errno::ENOENT
   -------------
   No such file or directory @ rb_sysopen - /etc/openvpn/default/keys/ta.key

   Cookbook Trace:
   ---------------
     /tmp/kitchen/cache/cookbooks/openvpn/recipes/default.rb:107:in `read'
     /tmp/kitchen/cache/cookbooks/openvpn/recipes/default.rb:107:in `rescue in from_file'
     /tmp/kitchen/cache/cookbooks/openvpn/recipes/default.rb:100:in `from_file'
     /tmp/kitchen/cache/cookbooks/openvpn_test/recipes/bridged.rb:16:in `from_file'

   Relevant File Content:
   ----------------------
   /tmp/kitchen/cache/cookbooks/openvpn/recipes/default.rb:

   100:    begin
   101:      ta_item = Hash(Chef::EncryptedDataBagItem.load("openvpn-#{server_name}", 'openvpn-ta')) if config['use_tls_auth']
   102:    rescue Net::HTTPServerException
   103:      # Generate ta.key file since there isn't a data bag yet
   104:      execute "openvpn --genkey --secret /etc/openvpn/#{server_name}/keys/ta.key" do
   105:        not_if { File.exist?("/etc/openvpn/#{server_name}/keys/ta.key") }
   106:      end
   107>>     key_data = File.read("/etc/openvpn/#{server_name}/keys/ta.key")
   108:  
   109:      ta_item = {
   110:        'id' => 'openvpn-ta',
   111:        'ta' => key_data
   112:      }
   113:  
   114:      databag_item = Chef::DataBagItem.from_hash(
   115:        Chef::EncryptedDataBagItem.encrypt_data_bag_item(
   116:          ta_item,
```

**Comment by strangeman** [comment]
Now (after merging https://github.com/express42-cookbooks/openvpn/pull/10 and https://github.com/express42-cookbooks/openvpn/pull/11) all test suites runs succesfully
